spring:
  application:
    name: commerce

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commerce-db
    username: root
    password: 1234

  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true
        use_sql_comments: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace